### ISSUE TITLE
"Uppsss...Page not found" should be "Ooppsss... Page not found"

### ISSUE THREAD

**Issue by tgrosser** [cloudogu/ces-theme#3]
"Ooppsss" looks more like written english. A blank between Ooppsss... and Page not found looks better.

**Comment by ischindler** [comment]
What about "Oops! Page not found"? Or do we want the repetition of "p" and "s"?

**Comment by tgrosser** [comment]
Yes, "Oops" is better

**Comment by sdorra** [comment]
Fixed with [857c4cb8](https://github.com/cloudogu/ces-theme/commit/857c4cb8e061989299b9a51ea6e8b6b841c6fd15).
